GET http://localhost:5050/users 

############

POST http://localhost:5050/users HTTP/1.1
content-type: application/json

{
     "firstname": "user6",
     "lastname": "user6",
     "username":"user6",
      "email": "user6@yahoo.it",
      "password": "user6abcde",
      "age": 38,
      "role":"user"
     }

############

PATCH http://localhost:5050/users/646f34aa85362d85e147a9e7 HTTP/1.1
content-type: application/json

{
   
    "email": "jwt@jwt.com",
    "password": "jwt123456"
}